### ISSUE TITLE
ICE when building match-stress

### ISSUE THREAD

**Issue by klensy** [rust-lang/rustc-perf#1665]
Didn't bisected where that started, but https://perf.rust-lang.org/status.html
<details>
```
Cannot compile match-stress

Caused by:
    expected success, got exit status: 101
    
    stderr= Documenting match-stress v0.1.0 (/tmp/.tmpUt7JXo)
    warning: unclosed HTML tag `baz`
       --> src/macros.rs:39:23
        |
    39  |                       $(#[$variant_attr])*
        |                         ^^^^^^^^^^^^^^^^
        |
       ::: src/expr.rs:15:1
        |
    15  | / ast_enum_of_structs! {
    16  | |     pub enum ExprKind {
    17  | |         /// A `box x` expression.
    18  | |         pub Box(ExprBox {
    ...   |
    348 | |     }
    349 | | }
        | |_- in this macro invocation
        |
        = note: `#[warn(rustdoc::invalid_html_tags)]` on by default
        = note: this warning originates in the macro `ast_enum_of_structs` (in Nightly builds, run with -Z macro-backtrace for more info)
    help: try marking as source code
        |
    39  |                     $(`#[$variant_attr]`)*
        |                       +                +
    
    warning: unclosed HTML tag `baz`
       --> src/macros.rs:6:11
        |
    6   |           $(#[$attr])*
        |             ^^^^^^^^
        |
       ::: src/expr.rs:15:1
        |
    15  | / ast_enum_of_structs! {
    16  | |     pub enum ExprKind {
    17  | |         /// A `box x` expression.
    18  | |         pub Box(ExprBox {
    ...   |
    348 | |     }
    349 | | }
        | |_- in this macro invocation
        |
        = note: this warning originates in the macro `ast_struct` which comes from the expansion of the macro `ast_enum_of_structs` (in Nightly builds, run with -Z macro-backtrace for more info)
    help: try marking as source code
        |
    6   |         $(`#[$attr]`)*
        |           +        +
    
    thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', src/librustdoc/html/format.rs:818:37
    stack backtrace:
       0:     0x7ffff3b26fc1 - std::backtrace_rs::backtrace::libunwind::trace::hf36f05c203408ba8
                                   at /rustc/e55147822ced7759651867efebb824fff4c64a43/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
       1:     0x7ffff3b26fc1 - std::backtrace_rs::backtrace::trace_unsynchronized::hf905dda5cfb54ae1
                                   at /rustc/e55147822ced7759651867efebb824fff4c64a43/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
       2:     0x7ffff3b26fc1 - std::sys_common::backtrace::_print_fmt::h29bc3e8aa54f3075
                                   at /rustc/e55147822ced7759651867efebb824fff4c64a43/library/std/src/sys_common/backtrace.rs:65:5
       3:     0x7ffff3b26fc1 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h106800685546d532
                                   at /rustc/e55147822ced7759651867efebb824fff4c64a43/library/std/src/sys_common/backtrace.rs:44:22
       4:     0x7ffff3b8d49c - core::fmt::rt::Argument::fmt::he8efc1f0f06a1b0b
                                   at /rustc/e55147822ced7759651867efebb824fff4c64a43/library/core/src/fmt/rt.rs:138:9
       5:     0x7ffff3b8d49c - core::fmt::write::h9ceb546df37ed1dc
                                   at /rustc/e55147822ced7759651867efebb824fff4c64a43/library/core/src/fmt/mod.rs:1094:21
       6:     0x7ffff3b195ce - std::io::Write::write_fmt::h4ca1a0e267037e6c
                                   at /rustc/e55147822ced7759651867efebb824fff4c64a43/library/std/src/io/mod.rs:1714:15
       7:     0x7ffff3b26dd5 - std::sys_common::backtrace::_print::h6255409db13d7aad
                                   at /rustc/e55147822ced7759651867efebb824fff4c64a43/library/std/src/sys_common/backtrace.rs:47:5
       8:     0x7ffff3b26dd5 - std::sys_common::backtrace::print::hb7b470af5d5df607
                                   at /rustc/e55147822ced7759651867efebb824fff4c64a43/library/std/src/sys_common/backtrace.rs:34:9
       9:     0x7ffff3b29e2a - std::panicking::panic_hook_with_disk_dump::{{closure}}::h2ab32bdbb0159cf7
                                   at /rustc/e55147822ced7759651867efebb824fff4c64a43/library/std/src/panicking.rs:278:22
      10:     0x7ffff3b29ac3 - std::panicking::panic_hook_with_disk_dump::h372ec2feabbf1856
                                   at /rustc/e55147822ced7759651867efebb824fff4c64a43/library/std/src/panicking.rs:312:9
      11:     0x7ffff6d3e5e9 - rustc_driver_impl[ba4ec6e8ba8adb4f]::install_ice_hook::{closure#0}
      12:     0x7ffff3b2a6d0 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h069382ae6cfcf76b
                                   at /rustc/e55147822ced7759651867efebb824fff4c64a43/library/alloc/src/boxed.rs:2021:9
      13:     0x7ffff3b2a6d0 - std::panicking::rust_panic_with_hook::h10a45c4c648c1264
                                   at /rustc/e55147822ced7759651867efebb824fff4c64a43/library/std/src/panicking.rs:733:13
      14:     0x7ffff3b2a411 - std::panicking::begin_panic_handler::{{closure}}::h6c1d0c752982d963
                                   at /rustc/e55147822ced7759651867efebb824fff4c64a43/library/std/src/panicking.rs:619:13
      15:     0x7ffff3b27426 - std::sys_common::backtrace::__rust_end_short_backtrace::h129c4f9e8ed0ddce
                                   at /rustc/e55147822ced7759651867efebb824fff4c64a43/library/std/src/sys_common/backtrace.rs:151:18
      16:     0x7ffff3b2a1a2 - rust_begin_unwind
                                   at /rustc/e55147822ced7759651867efebb824fff4c64a43/library/std/src/panicking.rs:617:5
      17:     0x7ffff3b89853 - core::panicking::panic_fmt::he49e630e55f0a8d3
                                   at /rustc/e55147822ced7759651867efebb824fff4c64a43/library/core/src/panicking.rs:67:14
      18:     0x7ffff3b898e3 - core::panicking::panic::hc5784792bc7cb45d
                                   at /rustc/e55147822ced7759651867efebb824fff4c64a43/library/core/src/panicking.rs:117:5
      19:     0x555555a544c2 - rustdoc[53dda7635e5b461]::html::format::resolved_path
      20:     0x555555a55fe4 - rustdoc[53dda7635e5b461]::html::format::fmt_type
      21:     0x555555a55d34 - rustdoc[53dda7635e5b461]::html::format::fmt_type
      22:     0x555555b31e3c - <rustdoc[53dda7635e5b461]::clean::types::FnDecl>::inner_full_print
      23:     0x7ffff3b8d42e - core::fmt::rt::Argument::fmt::he8efc1f0f06a1b0b
                                   at /rustc/e55147822ced7759651867efebb824fff4c64a43/library/core/src/fmt/rt.rs:138:9
      24:     0x7ffff3b8d42e - core::fmt::run::hc98e414e1c300148
                                   at /rustc/e55147822ced7759651867efebb824fff4c64a43/library/core/src/fmt/mod.rs:1142:11
      25:     0x7ffff3b8d42e - core::fmt::write::h9ceb546df37ed1dc
                                   at /rustc/e55147822ced7759651867efebb824fff4c64a43/library/core/src/fmt/mod.rs:1110:26
      26:     0x555555a5ce0f - <rustdoc[53dda7635e5b461]::html::format::display_fn::WithFormatter<<rustdoc[53dda7635e5b461]::clean::types::FnDecl>::full_print::{closure#0}> as core[62a911fb8a6b8d32]::fmt::Display>::fmt
      27:     0x7ffff3b8d49c - core::fmt::rt::Argument::fmt::he8efc1f0f06a1b0b
                                   at /rustc/e55147822ced7759651867efebb824fff4c64a43/library/core/src/fmt/rt.rs:138:9
      28:     0x7ffff3b8d49c - core::fmt::write::h9ceb546df37ed1dc
                                   at /rustc/e55147822ced7759651867efebb824fff4c64a43/library/core/src/fmt/mod.rs:1094:21
      29:     0x555555a05481 - rustdoc[53dda7635e5b461]::html::render::print_item::print_item
      30:     0x555555af584d - <rustdoc[53dda7635e5b461]::html::render::context::Context>::render_item
      31:     0x555555afdc2c - <rustdoc[53dda7635e5b461]::html::render::context::Context as rustdoc[53dda7635e5b461]::formats::renderer::FormatRenderer>::item
      32:     0x5555558c5efb - <rustc_session[53aadc3a4a11a83c]::session::Session>::time::<core[62a911fb8a6b8d32]::result::Result<(), rustc_span[284840969ed7ad8]::ErrorGuaranteed>, rustdoc[53dda7635e5b461]::main_args::{closure#1}::{closure#0}::{closure#0}::{closure#1}>
      33:     0x555555b0f375 - <rustc_middle[20c188538825ccb6]::ty::context::GlobalCtxt>::enter::<rustdoc[53dda7635e5b461]::main_args::{closure#1}::{closure#0}::{closure#0}, core[62a911fb8a6b8d32]::result::Result<(), rustc_span[284840969ed7ad8]::ErrorGuaranteed>>
      34:     0x555555a21991 - <scoped_tls[75d8cda12649de3e]::ScopedKey<rustc_span[284840969ed7ad8]::SessionGlobals>>::set::<rustc_interface[dffcb180bff0047d]::interface::run_compiler<core[62a911fb8a6b8d32]::result::Result<(), rustc_span[284840969ed7ad8]::ErrorGuaranteed>, rustdoc[53dda7635e5b461]::main_args::{closure#1}>::{closure#0}, core[62a911fb8a6b8d32]::result::Result<(), rustc_span[284840969ed7ad8]::ErrorGuaranteed>>
      35:     0x555555ad5de9 - std[9dc2aba4213ab54a]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[dffcb180bff0047d]::util::run_in_thread_pool_with_globals<rustc_interface[dffcb180bff0047d]::interface::run_compiler<core[62a911fb8a6b8d32]::result::Result<(), rustc_span[284840969ed7ad8]::ErrorGuaranteed>, rustdoc[53dda7635e5b461]::main_args::{closure#1}>::{closure#0}, core[62a911fb8a6b8d32]::result::Result<(), rustc_span[284840969ed7ad8]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[62a911fb8a6b8d32]::result::Result<(), rustc_span[284840969ed7ad8]::ErrorGuaranteed>>
      36:     0x555555bc8611 - <<std[9dc2aba4213ab54a]::thread::Builder>::spawn_unchecked_<rustc_interface[dffcb180bff0047d]::util::run_in_thread_pool_with_globals<rustc_interface[dffcb180bff0047d]::interface::run_compiler<core[62a911fb8a6b8d32]::result::Result<(), rustc_span[284840969ed7ad8]::ErrorGuaranteed>, rustdoc[53dda7635e5b461]::main_args::{closure#1}>::{closure#0}, core[62a911fb8a6b8d32]::result::Result<(), rustc_span[284840969ed7ad8]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[62a911fb8a6b8d32]::result::Result<(), rustc_span[284840969ed7ad8]::ErrorGuaranteed>>::{closure#1} as core[62a911fb8a6b8d32]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
      37:     0x7ffff3b34dc5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h9b78fd6a59b0f211
                                   at /rustc/e55147822ced7759651867efebb824fff4c64a43/library/alloc/src/boxed.rs:2007:9
      38:     0x7ffff3b34dc5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h05bd07659b9314d9
                                   at /rustc/e55147822ced7759651867efebb824fff4c64a43/library/alloc/src/boxed.rs:2007:9
      39:     0x7ffff3b34dc5 - std::sys::unix::thread::Thread::new::thread_start::h75483e5175f4e129
                                   at /rustc/e55147822ced7759651867efebb824fff4c64a43/library/std/src/sys/unix/thread.rs:108:17
      40:     0x7ffff31ed6db - start_thread
                                   at /build/glibc-CVJwZb/glibc-2.27/nptl/pthread_create.c:463
      41:     0x7ffff2b7861f - clone
                                   at /build/glibc-CVJwZb/glibc-2.27/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
      42:                0x0 - <unknown>
    
    error: the compiler unexpectedly panicked. this is a bug.
    
    note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-rustdoc&template=ice.md
    
    note: please attach the file at `/tmp/.tmpUt7JXo/rustc-ice-2023-07-25T17:41:21.708802397Z-19919.txt` to your bug report
    
    note: compiler flags: --crate-type lib -Z incremental-verify-ich -Z self-profile=/tmp/.tmpUt7JXo/self-profile-output
    
    note: some of the compiler flags provided by cargo are hidden
    
    query stack during panic:
    end of query stack
    thread 'main' panicked at 'command did not complete successfully: LC_NUMERIC="C" RUSTC_FORCE_INCR_COMP_ARTIFACT_HEADER="rustc-perf" RUSTC_FORCE_RUSTC_VERSION="rustc-perf" "perf" "stat" "-x;" "-e" "instructions:u,cycles:u,task-clock,cpu-clock,faults,context-switches,branch-misses,cache-misses" "--log-fd" "1" "setarch" "x86_64" "-R" "/home/collector/rustc-perf/cache/e55147822ced7759651867efebb824fff4c64a43/bin/rustdoc" "--crate-type" "lib" "--crate-name" "match_stress" "src/lib.rs" "-o" "/tmp/.tmpUt7JXo/target/doc" "--error-format=json" "--json=diagnostic-rendered-ansi,artifacts,future-incompat" "-C" "metadata=4d8968d0b7ccda8a" "-L" "dependency=/tmp/.tmpUt7JXo/target/debug/deps" "--crate-version" "0.1.0" "-Adeprecated" "-Aunknown-lints" "-Zincremental-verify-ich" "-Zself-profile=/tmp/.tmpUt7JXo/self-profile-output"', collector/src/bin/rustc-fake.rs:24:5
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    warning: `match-stress` (lib doc) generated 2 warnings
    error: could not document `match-stress`
    
    Caused by:
      process didn't exit successfully: `/home/collector/rustc-perf/target/release/rustdoc-fake --crate-type lib --crate-name match_stress src/lib.rs -o /tmp/.tmpUt7JXo/target/doc --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --wrap-rustc-with PerfStatSelfProfile -C metadata=4d8968d0b7ccda8a -L dependency=/tmp/.tmpUt7JXo/target/debug/deps --crate-version 0.1.0` (exit status: 101) 
```
</details>

**Comment by Kobzol** [comment]
This was only caused by a try build, right? https://github.com/rust-lang/rust/pull/113374

Maybe the status page should include some information about the commit, to have a bigger warning if the error happened on a merge commit (as opposed to a try build).

**Comment by klensy** [comment]
At least link to PR will be good too.

Maybe log for last X perf runs, so if there any error, it will be visible there.
