### ISSUE TITLE
site: server panics on access

### ISSUE THREAD

**Issue by lcnr** [rust-lang/rustc-perf#665]
I first ran:
```
./target/release/collector --filter inflate --output-repo ../benches bench_local \
--rustc ../rust2/build/x86_64-unknown-linux-gnu/stage2/bin/rustc --cargo ../.cargo/bin/cargo const-opt
```
and then
```
./target/release/site const-opt/
```
Accessing `http://localhost:2346/compare.html` now resulted in the following panics:
```
Starting server with port=2346
Loading complete.
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', site/src/server.rs:62:16
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', site/src/server.rs:62:16
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', site/src/server.rs:62:16
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', site/src/server.rs:62:16
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', site/src/server.rs:62:16
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', site/src/server.rs:62:16
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', site/src/server.rs:62:16
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', site/src/server.rs:62:16
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', site/src/server.rs:62:16
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', site/src/server.rs:62:16
```
localhost console:
```
The script from “http://localhost:2346/shared.js” was loaded even though its MIME type (“”) is not a valid JavaScript MIME type. compare.html
Error fetching info: shared.js:103:17
TypeError: "NetworkError when attempting to fetch resource. shared.js:104:17"
```
Backtrace:
```
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1504
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:511
  11: rust_begin_unwind
             at src/libstd/panicking.rs:419
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:111
  13: core::panicking::panic
             at src/libcore/panicking.rs:54
  14: core::option::Option<T>::unwrap
             at /home/programming/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/macros/mod.rs:34
  15: site::server::handle_info
             at site/src/server.rs:62
  16: core::ops::function::FnOnce::call_once
             at /home/programming/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/ops/function.rs:232
  17: site::server::Server::handle_get
             at ./site/src/server.rs:837
  18: site::server::serve_req::{{closure}}
             at ./site/src/server.rs:995
  19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/programming/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/future/mod.rs:66
  20: <futures_util::future::future::inspect::Inspect<Fut,F> as core::future::future::Future>::poll
             at /home/programming/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/future/future/inspect.rs:42
  21: <hyper::proto::h1::dispatch::Server<S,hyper::body::body::Body> as hyper::proto::h1::dispatch::Dispatch>::poll_msg
             at /home/programming/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.2/src/proto/h1/dispatch.rs:474
  22: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_write
             at /home/programming/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.2/src/proto/h1/dispatch.rs:283
  23: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_loop
             at /home/programming/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.2/src/proto/h1/dispatch.rs:150
  24: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_inner
             at /home/programming/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.2/src/proto/h1/dispatch.rs:126
  25: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch
             at /home/programming/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.2/src/proto/h1/dispatch.rs:109
  26: <hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T> as core::future::future::Future>::poll
             at /home/programming/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.2/src/proto/h1/dispatch.rs:409
  27: <hyper::server::conn::ProtoServer<T,B,S,E> as core::future::future::Future>::poll
             at /home/programming/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.2/src/server/conn.rs:773
  28: <hyper::server::conn::upgrades::UpgradeableConnection<I,S,E> as core::future::future::Future>::poll
             at /home/programming/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.2/src/server/conn.rs:949
  29: <hyper::server::conn::spawn_all::NewSvcTask<I,N,S,E,W> as core::future::future::Future>::poll
             at /home/programming/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.2/src/server/conn.rs:889
  30: tokio::task::core::Core<T>::poll
             at /home/programming/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/task/core.rs:128
  31: tokio::task::harness::Harness<T,S>::poll::{{closure}}::{{closure}}
             at /home/programming/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/task/harness.rs:119
  32: core::ops::function::FnOnce::call_once
             at /home/programming/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/ops/function.rs:232
  33: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /home/programming/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panic.rs:318
  34: std::panicking::try::do_call
             at /home/programming/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panicking.rs:331
  35: std::panicking::try
             at /home/programming/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panicking.rs:274
  36: std::panic::catch_unwind
             at /home/programming/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panic.rs:394
  37: tokio::task::harness::Harness<T,S>::poll::{{closure}}
             at /home/programming/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/task/harness.rs:100
  38: tokio::loom::std::causal_cell::CausalCell<T>::with_mut
             at /home/programming/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/loom/std/causal_cell.rs:41
  39: tokio::task::harness::Harness<T,S>::poll
             at /home/programming/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/task/harness.rs:99
  40: tokio::runtime::thread_pool::worker::GenerationGuard::run_task
  41: tokio::runtime::thread_pool::worker::GenerationGuard::run
  42: std::thread::local::LocalKey<T>::with
  43: tokio::runtime::thread_pool::worker::Worker::run
  44: tokio::task::core::Core<T>::poll
  45: tokio::task::harness::Harness<T,S>::poll
  46: tokio::runtime::blocking::pool::Inner::run
  47: tokio::runtime::context::enter
```

**Comment by nnethercote** [comment]
You're almost there :)  You need this:
```
./target/release/site ../benches
```
However, there has been a recent change in the data format, you might get a message about having to run a command called `ingest`. If so, you can run `ingest database ../benches/timings/$FILE`, where `$FILE` is the `.sz` file within that directory. The you can run `./target/release/site database`. (Sorry this isn't documented yet, it's a very recent change.)

**Comment by Mark-Simulacrum** [comment]
Yeah, there will soon be another (and this time final, I hope) change in the data format, FWIW. The version in master is a pain to manage, especially when collecting locally (and didn't work out as well as I had hoped in production, even though initial testing showed some promise).

**Comment by Mark-Simulacrum** [comment]
I believe this is fixed; documentation in READMEs in the site and collector directories has been updated. If there are further questions or problems feel free to open another issue.
