### ISSUE TITLE
thread 'main' panicked at 'unexpected file ...'

### ISSUE THREAD

**Issue by osa1** [rust-lang/rustc-perf#850]
Using master branch (e4e5da47a505f9aff5c76cb7f26701fd0d6043cf)

In a clean tree, if I run

```
./target/release/collector \
    profile_local \
    self-profile \
    /home/omer/rust/rust/build/x86_64-unknown-linux-gnu/stage1/bin/rustc \
    test
```

I get this output:

```
Profiling with SelfProfile
46 benchmarks remaining
Preparing await-call-tree
Running await-call-tree: Check + [Full, IncrFull, IncrUnchanged, IncrPatched]
thread 'main' panicked at 'unexpected file "results/Zsp-test-await-call-tree-Check-Full/await_call_tree-4903.mm_profdata"', collector/src/execute.rs:884:25
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:435:5
   2: <collector::execute::ProfileProcessor as collector::execute::Processor>::process_output
             at ./collector/src/execute.rs:884:25
   3: collector::execute::CargoProcess::run_rustc
             at ./collector/src/execute.rs:424:23
   4: collector::execute::Benchmark::measure
             at ./collector/src/execute.rs:1242:21
   5: collector::main_result
             at ./collector/src/main.rs:763:21
   6: collector::main
             at ./collector/src/main.rs:441:11
   7: core::ops::function::FnOnce::call_once
             at /home/omer/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by tgnottingham** [comment]
This looks like it was fixed by commit 4fa8ee6362bdfeacc03781f484ee4f9593326bbe of #865.
